---
- name: Clone / update 3D-printer repos under ~pi/devs
  hosts: all
  become: false
  gather_facts: false

  vars:
    devs_dir: /home/pi/devs
    printer_config_dir: /home/pi/printer_data/config
    ratos_repo: "git@github.com:matti125/ratos-ratos2.git"
    ratos_version: master
    ratos_deploy_key: /home/pi/.ssh/github-ratos-ratos2

    # Leave empty for public HTTPS repos.
    # Set to an SSH deploy key path if you clone private repos via SSH.
    git_ssh_key_file: ""   # e.g. /home/pi/.ssh/github_deploy_key

    git_accept_hostkey: true

    repos:
    - name: cfg-expander
      repo: "https://github.com/matti125/cfg-expander.git"
      version: main

    - name: deploy-key-setup
      repo: "https://github.com/matti125/deploy-key-setup.git"
      version: main
    - name: ratemeter
      repo: "https://github.com/matti125/ratemeter.git"
      version: master

    - name: motors-sync
      repo: "https://github.com/MRX8024/motors-sync.git"
      version: hybrid-corexy-kinematics-support


  tasks:
    - name: Prompt for pi password (bootstrap only)
      ansible.builtin.pause:
        prompt: "Enter new password for user pi (leave blank to skip)"
        echo: false
      register: pi_password_prompt
      tags: [bootstrap, never]

    - name: Set pi password fact
      ansible.builtin.set_fact:
        pi_password: "{{ (pi_password_prompt.user_input | default('')) }}"
      tags: [bootstrap, never]

    - name: Ensure ll alias for interactive bash shells
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker: "# {mark} ANSIBLE LL ALIAS"
        block: |
          alias ll='ls -la'
      become: true
      tags: [bootstrap, never]

    - name: Select default local public key (bootstrap)
      ansible.builtin.set_fact:
        local_pubkey_path: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ lookup('env','HOME') + '/.ssh/id_ed25519.pub' }}"
            - "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
            - "{{ lookup('env','HOME') + '/.ssh/id_ecdsa.pub' }}"
            - "{{ lookup('env','HOME') + '/.ssh/id_dsa.pub' }}"
          skip: true
      tags: [bootstrap, never]

    - name: Ensure a local public key was found (bootstrap)
      ansible.builtin.assert:
        that:
          - local_pubkey_path | length > 0
        fail_msg: "No local SSH public key found in ~/.ssh (id_ed25519.pub, id_rsa.pub, id_ecdsa.pub, id_dsa.pub)."
      tags: [bootstrap, never]

    - name: Ensure ~/devs exists
      ansible.builtin.file:
        path: "{{ devs_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure printer config dir exists
      ansible.builtin.file:
        path: "{{ printer_config_dir }}"
        state: directory
        mode: "0755"

    - name: Ensure ~/.influxdbv2 exists
      ansible.builtin.file:
        path: /home/pi/.influxdbv2
        state: directory
        owner: pi
        group: pi
        mode: "0700"

    - name: Copy InfluxDB v2 configs file
      ansible.builtin.copy:
        src: files/.influxdbv2/configs
        dest: /home/pi/.influxdbv2/configs
        owner: pi
        group: pi
        mode: "0700"

    - name: Ensure ~/.ssh exists
      ansible.builtin.file:
        path: /home/pi/.ssh
        state: directory
        owner: pi
        group: pi
        mode: "0700"

    - name: Add GitHub host keys
      ansible.builtin.known_hosts:
        path: /home/pi/.ssh/known_hosts
        name: github.com
        key: "{{ item }}"
        state: present
      loop:
        - "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"
        - "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg="
        - "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="

    - name: Ensure known_hosts is owned by pi
      ansible.builtin.file:
        path: /home/pi/.ssh/known_hosts
        owner: pi
        group: pi
        mode: "0644"

    - name: Copy SSH private key
      ansible.builtin.copy:
        src: files/.ssh/github-ratos-ratos2
        dest: /home/pi/.ssh/github-ratos-ratos2
        owner: pi
        group: pi
        mode: "0600"

    - name: Copy SSH public key
      ansible.builtin.copy:
        src: files/.ssh/github-ratos-ratos2.pub
        dest: /home/pi/.ssh/github-ratos-ratos2.pub
        owner: pi
        group: pi
        mode: "0644"


    - name: Add authorized key for pi (bootstrap)
      ansible.builtin.authorized_key:
        user: pi
        key: "{{ lookup('ansible.builtin.file', local_pubkey_path) }}"
        state: present
      become: true
      tags: [bootstrap, never]

    - name: Initialize git repo in printer config dir
      ansible.builtin.command: git init
      args:
        chdir: "{{ printer_config_dir }}"
        creates: "{{ printer_config_dir }}/.git"

    - name: Ensure ratos repo remote exists
      ansible.builtin.command: git remote add origin {{ ratos_repo }}
      args:
        chdir: "{{ printer_config_dir }}"
      register: ratos_remote_add
      changed_when: ratos_remote_add.rc == 0
      failed_when: ratos_remote_add.rc != 0 and ("already exists" not in ratos_remote_add.stderr)

    - name: Fetch ratos repo
      ansible.builtin.command: git fetch --depth=1 origin {{ ratos_version }}
      args:
        chdir: "{{ printer_config_dir }}"
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ ratos_deploy_key }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes"

    - name: Restore ratos .gitignore and local folder only
      ansible.builtin.command: git checkout origin/{{ ratos_version }} -- .gitignore local
      args:
        chdir: "{{ printer_config_dir }}"
      environment:
        GIT_SSH_COMMAND: "ssh -i {{ ratos_deploy_key }} -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes"

    - name: Clone/update repos
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ devs_dir }}/{{ item.name }}"
        version: "{{ item.version | default('HEAD') }}"
        update: true
        force: false
        accept_hostkey: "{{ git_accept_hostkey }}"
        key_file: "{{ (git_ssh_key_file | length > 0) | ternary(git_ssh_key_file, omit) }}"
      loop: "{{ repos }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Stat ratemeter unit source
      ansible.builtin.stat:
        path: "{{ devs_dir }}/ratemeter/ratemeter.service"
        checksum_algorithm: sha256
      register: ratemeter_unit_src

    - name: Stat ratemeter unit destination
      ansible.builtin.stat:
        path: /etc/systemd/system/ratemeter.service
        checksum_algorithm: sha256
      register: ratemeter_unit_dest

    - name: Copy ratemeter systemd unit when different
      ansible.builtin.copy:
        src: "{{ devs_dir }}/ratemeter/ratemeter.service"
        dest: /etc/systemd/system/ratemeter.service
        owner: root
        group: root
        mode: "0644"
        remote_src: true
      become: true
      register: ratemeter_unit_copy
      when:
        - not ratemeter_unit_dest.stat.exists or ratemeter_unit_src.stat.checksum != ratemeter_unit_dest.stat.checksum

    - name: Reload systemd units
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
      when: ratemeter_unit_copy.changed

    - name: Enable and start ratemeter service
      ansible.builtin.systemd:
        name: ratemeter.service
        enabled: true
        state: started
      become: true
      when: ratemeter_unit_copy.changed

    - name: Set pi password once
      ansible.builtin.user:
        name: pi
        password: "{{ pi_password | password_hash('sha512') }}"
      when:
        - (pi_password | default('')) | length > 0
      become: true
      tags: [bootstrap, never]



       
